//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfringementCustomerWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactu
    {
        public int id { get; set; }
        public string CustomerName { get; set; }
        public string Email { get; set; }
        public string SubjectText { get; set; }
        public string InfringementNumbers { get; set; }
        public string BodyContent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ClientIp { get; set; }
        public string BrowserName { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
