//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfringementCustomerWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class infringementEntities : DbContext
    {
        public infringementEntities()
            : base("name=infringementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<carmodel> carmodels { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<contactu> contactus { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<infringement> infringements { get; set; }
        public virtual DbSet<infringement_number_encryption> infringement_number_encryption { get; set; }
        public virtual DbSet<infringement_payment> infringement_payment { get; set; }
        public virtual DbSet<infringementpicture> infringementpictures { get; set; }
        public virtual DbSet<infringementstatu> infringementstatus { get; set; }
        public virtual DbSet<infringementtype> infringementtypes { get; set; }
        public virtual DbSet<make> makes { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<parking_location> parking_location { get; set; }
        public virtual DbSet<emailid> emailids { get; set; }
    }
}
