//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfringementCustomerWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class infringementpicture
    {
        public int Id { get; set; }
        public int InfringementId { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
    
        public virtual infringement infringement { get; set; }
    }
}
