//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfringementCustomerWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class infringement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public infringement()
        {
            this.infringementpictures = new HashSet<infringementpicture>();
        }
    
        public int Id { get; set; }
        public System.DateTime IncidentTime { get; set; }
        public string Number { get; set; }
        public string Rego { get; set; }
        public int ParkingLocationId { get; set; }
        public Nullable<int> MakeId { get; set; }
        public string Model { get; set; }
        public int InfringementTypeId { get; set; }
        public decimal Amount { get; set; }
        public string Comment { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> UploadTime { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public int StatusId { get; set; }
        public Nullable<bool> Pay { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string OtherMake { get; set; }
        public string OtherModel { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> AfterDueDate { get; set; }
        public string OwnerName { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string Suburb { get; set; }
        public string PostCode { get; set; }
        public string CountryId { get; set; }
        public string CityName { get; set; }
        public string OtherInfringementType { get; set; }
        public Nullable<int> GeneratedFrom { get; set; }
        public string PaymentType { get; set; }
        public Nullable<int> CityId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infringementpicture> infringementpictures { get; set; }
        public virtual make make { get; set; }
        public virtual infringementtype infringementtype { get; set; }
        public virtual parking_location parking_location { get; set; }
    }
}
