//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfringementWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class infringement_payment
    {
        public int Id { get; set; }
        public int InfringementId { get; set; }
        public string TransactionNumber { get; set; }
        public string PaymentResult { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    }
}
